### ISSUE TITLE
Guide to run on ESP32

### ISSUE THREAD

**Issue by dmckminard** [bridadan/libsnapcast#1]
Hello,
Your project seems pretty cool !

It would be very interesting if you could write a ReadMe to make it run.
At the moment, this is supposed to run on an ESP32 module with only a sound card, right ?

Nice job !

**Comment by bridadan** [comment]
Hi there, yeah it does run on an ESP32 with an I2S DAC attached. It would actually work with the internal DAC as well, however the audio quality really isn't very good so I've been using the external DAC.

Its not currently in a stable state, but if you're interested in experimenting you can find my example application here: https://github.com/bridadan/esp-adf/tree/snapcast/examples/player/snapcast. Note that its on the `snapcast` branch, not the `master` branch. This is the application I've been using to test this library on the ESP32.

I would like to have a test application running natively on Linux as well for easier testing. If you're interested in working on a part just let me know and I'll try to point you in the right direction!

**Comment by isaactzab** [comment]
Could be possible that it works with decoder ic? like this one?
http://www.vlsi.fi/en/products/vs1063.html

**Comment by bridadan** [comment]
I really don't know! I've been using this DAC: https://www.amazon.com/HiLetgo-Lossless-Digital-Converter-Raspberry/dp/B07Q9K5MT8/ref=sr_1_1?keywords=pcm5102&qid=1579798333&sr=8-1

**Comment by NathanTct** [comment]
Hi there, I'm quite new to this kind of projects but I would love to make it work ! 
I am trying to use libsnapcast with an ESP32S board (literally only the ESP32 on it) with PCM5102 connected to it. I also took a look at your snapcast example quoted in your previous answer, but i can't run neither libsnapcast nor snapcast example. It looks like because esp-adf tries to initialize LyraT board while I have ESP32S board. Do you know if there is a solution to this problem ? And do I need to cross esp-adf and libsnapcast ? I'm not sure to perfectly understand how to use your project.. 
Again I'm quite new, but I'd love to contribute to this project, even if my skills are quite limited for now! But if I can't even flash the project it sounds complicated haha !

**Comment by bridadan** [comment]
Hi @NathanTct, sorry for the late reply!

I've been using this board: https://www.amazon.com/gp/product/B07PR9T5R5/ref=ppx_yo_dt_b_asin_title_o07_s00?ie=UTF8&psc=1

In my example I linked above I actually modified the I2S pins in the LyraT board source code to match my board. Here's the commit that makes the modification: https://github.com/bridadan/esp-adf/commit/e54fa09de824a73cfd8d46ddf55d0208fab0622d

So you may have to do something similar with your board.

As far as compiling the snapcast example, I think the general steps should be something like:

```
git clone https://github.com/bridadan/esp-adf.git
cd esp-adf
git checkout snapcast
git submodule update --init --recursive
# follow the normal ESP ADF setup
# be sure to set the ADF_PATH variable: https://github.com/espressif/esp-adf/blob/a0f3aa0aad3bda6fffdbdbc579096908030776b1/docs/en/get-started/index.rst#setup-path-to-esp-adf
cd examples/player/snapcast
make menuconfig
make flash monitor
```

Those may not be 100% right, but hopefully that's enough to get you going. It's been about 4 months since I've looked at any of this so I'm a little rusty!

**Comment by miLORD1337** [comment]
Thanks for the heads up and the great work! I've been trying as well. I can flash it alright, but I won't get any sound.
You said you modified the pins and I'm curious how to do it for my board (ESP32 NodeMCU). If you use the ESP8266 NodeMCU, I don't understand the pinout. There are no pins 25, 26, and 35, are there? So you get away with only SCLK on pin 14? 

Could you please elaborate on which pin is which? I thought there needed to be BCK, DOUT, LCK and optionally SCK...

I got the IDF I2S example to work, so my I2S hardware wiring is okay I guess...

Thank you in advance!

Edit: ~~Seems like I have to write my own driver for the PCM5102A to work with the audio_HAL...~~ Actually, we use the exact same DAC, so it has to work! :P

**Comment by miLORD1337** [comment]
Never mind, got it working now and added an EQ because I wasn't happy with the sound of the PCM5102A out of the box.

The sound stutters though, I was wondering if you experienced those issues as well? It might just be because it's not synced yet...

**Comment by bridadan** [comment]
Glad you were able to get it playing! Yeah the stuttering definitely occurs. That could definitely be due to the lack of sync or perhaps buffering, I haven't had time to look into it.

**Comment by miLORD1337** [comment]
Thanks for getting back so quick. From what Jørgen said over at Snapcast I'm now guessing it's both. I unfortunately bought the WROOM, which has no PSRAM, whereas the WROVER has 8 MB of that.

So if you want to be on the safe side regarding buffering, definitely go for the WROVER.

**Comment by bridadan** [comment]
I'll go ahead and close this since it sounds like folks were able to get started at least, feel free to reopen this or open another issue if you have further questions.
